dist:
  name: otelcol-dev

receivers:
  - gomod: "github.com/castai/otelreceiver v0.0.0"

processors:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.80.0"

exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter v0.80.0"

replaces:
  - github.com/castai/otelreceiver => ../../receiver
  - google.golang.org/genproto => google.golang.org/genproto v0.0.0-20230530153820-e85fd2cbaebc
